---
- name: download wp cli
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar 
           dest=/usr/local/bin/wp-cli.phar
           mode=755


- name: rename binary
  command: mv wp-cli.phar wp chdir=/usr/local/bin creates=/usr/local/bin/wp
